### PR TITLE
Extend compatibility to python 3.6 and 3.7; deprecate python 2.7 and 3.3

### PR DESCRIPTION
**Pull request by memory**

### CODE REVIEW

**Comment by memory** [comment]
Oh boy, this just gets more and more fun.  Pylint 1.9 doesn't work with Python 3.7.  Pylint 2.x has dropped compatibility with py27.

**Comment by memory** [comment]
@kairoaraujo I think I'm inclined to just get ahead of the curve here, declare a 2.x release train and drop py2.x support in it entirely.  In the unlikely event that there are major changes that need to be made here, they can be backported into the 1.x tree.  Would that break your workflows?

**Comment by kairoaraujo** [comment]
IMHO, release as 1.4.0 compatible with Python 3.x only and keep 1.3.1  compatible with 2.7 and 3.5. So you can create a tag for both. In the future, if needed you can fix only 1.3.X

**Comment by kairoaraujo** [comment]
IMHO, release as 1.13.0 compatible with Python 3.x and keep 1.3.0 as compatible with 2.7 and 3.5. So you can create a tag for both. In the future, if needed you can fix only 1.12.

**Pull request merged**
